---
- name: Ensure admin group exists
  ansible.builtin.group:
    name: "{{ create_main_user_v_admin_group }}"
    state: present

- name: Allow admin group to have passwordless sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ create_main_user_v_admin_group }}'
    line: '%{{ create_main_user_v_admin_group }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Create dev user to admin group
  ansible.builtin.user:
    name: "{{ create_main_user_v_username }}"
    expires: -1
    groups: "{{ create_main_user_v_admin_group }}"
    shell: /bin/bash
    append: true
    state: present
    createhome: true
