---
- name: Create initial directories for vs code
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ v_vs_code_setup_username }}"
    group: "{{ v_vs_code_setup_username }}"
  loop:
    - '/ansible'
    - '/ansible/.vscode'
    - '/ansible/default_settings'
    - '/ansible/default_settings/vscode'
  register: create_dirs_result

- name: Debug - Show result of creating directories
  debug:
    msg: |
      Directory: {{ item.item }}
      Result: {{ item.result }}
    loop: "{{ create_dirs_result.results }}"
    verbosity: 3

- name: Copy extensions.json to default settings
  ansible.builtin.copy:
    src: "{{ role_path }}/files/extensions.json"
    dest: /ansible/default_settings/vscode/extensions.json
    mode: '0644'
    owner: "{{ v_vs_code_setup_username }}"
    group: "{{ v_vs_code_setup_username }}"
  register: copy_extensions_result

- name: Debug - Show result of copying extensions.json
  debug:
    msg: |
      Source: {{ item.item.src }}
      Destination: {{ item.item.dest }}
      Result: {{ item.result }}
    loop: "{{ copy_extensions_result.results }}"
    verbosity: 3

- name: Copy settings.json to default settings
  ansible.builtin.copy:
    src: "{{ role_path }}/templates/settings.json.j2"
    dest: /ansible/default_settings/vscode/settings.json
    mode: '0644'
    owner: "{{ v_vs_code_setup_username }}"
    group: "{{ v_vs_code_setup_username }}"
  register: copy_settings_result

- name: Debug - Show result of copying settings.json
  debug:
    msg: |
      Source: {{ item.item.src }}
      Destination: {{ item.item.dest }}
      Result: {{ item.result }}
    loop: "{{ copy_settings_result.results }}"
    verbosity: 3

- name: Copy extensions.json to actual settings
  ansible.builtin.copy:
    src: "{{ role_path }}/files/extensions.json"
    dest: /ansible/.vscode/extensions.json
    mode: '0644'
    owner: "{{ v_vs_code_setup_username }}"
    group: "{{ v_vs_code_setup_username }}"
  register: copy_extensions_actual_result

- name: Debug - Show result of copying extensions.json to actual settings
  debug:
    msg: |
      Source: {{ item.item.src }}
      Destination: {{ item.item.dest }}
      Result: {{ item.result }}
    loop: "{{ copy_extensions_actual_result.results }}"
    verbosity: 3

- name: Copy settings.json to actual settings
  ansible.builtin.copy:
    src: "{{ role_path }}/files/settings.json"
    dest: /ansible/.vscode/settings.json
    mode: '0644'
    owner: "{{ v_vs_code_setup_username }}"
    group: "{{ v_vs_code_setup_username }}"
  register: copy_settings_actual_result

- name: Debug - Show result of copying settings.json to actual settings
  debug:
    msg: |
      Source: {{ item.item.src }}
      Destination: {{ item.item.dest }}
      Result: {{ item.result }}
    loop: "{{ copy_settings_actual_result.results }}"
    verbosity: 3