---
- name: Create initial directories for vs code
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ v_vs_code_setup_username }}"
    group: "{{ v_vs_code_setup_username }}"
  loop:
    - '/ansible'
    - '/ansible/.vscode'
    - '/ansible/default_settings'
    - '/ansible/default_settings/vscode'

- name: Copy extensions.json to default settings
  ansible.builtin.copy:
    src: "{{ role_path }}/files/extensions.json"
    dest: /ansible/default_settings/vscode/extensions.json
    mode: '0644'
    owner: "{{ v_vs_code_setup_username }}"
    group: "{{ v_vs_code_setup_username }}"

- name: Copy settings.json to default settings
  ansible.builtin.copy:
    src: "{{ role_path }}/files/settings.json"
    dest: /ansible/default_settings/vscode/settings.json
    mode: '0644'
    owner: "{{ v_vs_code_setup_username }}"
    group: "{{ v_vs_code_setup_username }}"

- name: Copy extensions.json to actual settings
  ansible.builtin.copy:
    src: "{{ role_path }}/files/extensions.json"
    dest: /ansible/.vscode/extensions.json
    mode: '0644'
    owner: "{{ v_vs_code_setup_username }}"
    group: "{{ v_vs_code_setup_username }}"

- name: Copy settings.json to actual settings
  ansible.builtin.copy:
    src: "{{ role_path }}/files/settings.json"
    dest: /ansible/.vscode/settings.json
    mode: '0644'
    owner: "{{ v_vs_code_setup_username }}"
    group: "{{ v_vs_code_setup_username }}"
