---
- name: Create initial directories for vs code
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ vs_code_setup_v_username }}"
    group: "{{ vs_code_setup_v_admin_group }}"
  loop:
    - '/ansible'
    - '/ansible/.vscode'
    - '/ansible/default_settings'
    - '/ansible/default_settings/vscode'
  register: create_dirs_result

- name: Debug - Show result of creating directories
  debug:
    msg: |
      ============================================================
      RESULTADO DA CRIAÇÃO DOS DIRETÓRIOS
      ============================================================
      Status:
        Diretórios: {{ create_dirs_result.results | map(attribute='item') | list }}
        Paths: {{ create_dirs_result.results | map(attribute='path') | list }}
        Alterados: {{ create_dirs_result.results | map(attribute='changed') | list }}
      
      Permissões:
        Proprietários: {{ create_dirs_result.results | map(attribute='uid') | list }}
        Grupos: {{ create_dirs_result.results | map(attribute='gid') | list }}
        Modos: {{ create_dirs_result.results | map(attribute='mode') | list }}
      
      Resultados:
        Sucessos: {{ create_dirs_result.results | rejectattr('failed') | list | length }}
        Falhas: {{ create_dirs_result.results | selectattr('failed') | list | length }}
        Estado: {{ create_dirs_result.results | map(attribute='state') | list }}
      ============================================================
    verbosity: 3

- name: Copy extensions.json to default settings
  ansible.builtin.copy:
    src: "{{ role_path }}/files/extensions.json"
    dest: /ansible/default_settings/vscode/extensions.json
    mode: '0644'
    owner: "{{ vs_code_setup_v_username }}"
    group: "{{ vs_code_setup_v_admin_group }}"
  register: copy_extensions_result

- name: Debug - Show result of copying extensions.json
  debug:
    msg: |
      ================================
      RESULTADO DA CÓPIA DO SETTINGS.JSON
      ================================
      Source: {{ copy_extensions_result.src | default('N/A') }}
      Destination: {{ copy_extensions_result.dest | default('N/A') }}
      Changed: {{ copy_extensions_result.changed | default(false) }}
      Mode: {{ copy_extensions_result.mode | default('N/A') }}
      Failed: {{ copy_extensions_result.failed | default(false) }}
      ================================
      Dados Completos:
      {{ copy_extensions_result | to_nice_yaml }}
      ================================
    verbosity: 3

- name: Copy settings.json to default settings
  ansible.builtin.copy:
    src: "{{ role_path }}/templates/settings.json.j2"
    dest: /ansible/default_settings/vscode/settings.json
    mode: '0644'
    owner: "{{ vs_code_setup_v_username }}"
    group: "{{ vs_code_setup_v_admin_group }}"
  register: copy_settings_result

- name: Debug - Show result of copying settings.json
  debug:
    msg: |
      ================================
      RESULTADO DA CÓPIA DO SETTINGS.JSON
      ================================
      Source: {{ copy_settings_result.src | default('N/A') }}
      Destination: {{ copy_settings_result.dest | default('N/A') }}
      Changed: {{ copy_settings_result.changed | default(false) }}
      Mode: {{ copy_settings_result.mode | default('N/A') }}
      Failed: {{ copy_settings_result.failed | default(false) }}
      ================================      
      Dados Completos:
      {{ copy_settings_result | to_nice_yaml }}
      ================================
    verbosity: 3

- name: Copy extensions.json to actual settings
  ansible.builtin.copy:
    src: "{{ role_path }}/files/extensions.json"
    dest: /ansible/.vscode/extensions.json
    mode: '0644'
    owner: "{{ vs_code_setup_v_username }}"
    group: "{{ vs_code_setup_v_admin_group }}"
  register: copy_extensions_actual_result

- name: Debug - Show result of copying extensions.json to actual settings
  debug:
    msg: |
      ================================
      RESULTADO DA CÓPIA DO SETTINGS.JSON
      ================================
      Source: {{ copy_extensions_actual_result.src | default('N/A') }}
      Destination: {{ copy_extensions_actual_result.dest | default('N/A') }}
      Changed: {{ copy_extensions_actual_result.changed | default(false) }}
      Mode: {{ copy_extensions_actual_result.mode | default('N/A') }}
      Failed: {{ copy_extensions_actual_result.failed | default(false) }}
      ================================
      Dados Completos:
      {{ copy_extensions_actual_result | to_nice_yaml }}
      ================================
    verbosity: 3

- name: Copy settings.json to actual settings
  ansible.builtin.copy:
    src: "{{ role_path }}/files/settings.json"
    dest: /ansible/.vscode/settings.json
    mode: '0644'
    owner: "{{ vs_code_setup_v_username }}"
    group: "{{ vs_code_setup_v_admin_group }}"
  register: copy_settings_actual_result

- name: Debug - Show result of copying settings.json to actual settings
  debug:
    msg: |
      ================================
      RESULTADO DA CÓPIA DO SETTINGS.JSON
      ================================
      Source: {{ copy_settings_actual_result.src | default('N/A') }}
      Destination: {{ copy_settings_actual_result.dest | default('N/A') }}
      Changed: {{ copy_settings_actual_result.changed | default(false) }}
      Mode: {{ copy_settings_actual_result.mode | default('N/A') }}
      Failed: {{ copy_settings_actual_result.failed | default(false) }}
      ================================
      Dados Completos:
      {{ copy_settings_actual_result | to_nice_yaml }}
      ================================
    verbosity: 3