---
- name: Create the /dev/mqueue directory
  ansible.builtin.file:
    path: /dev/mqueue
    state: directory
    mode: '0755'
  become: true
  register: mqueue_result

- name: Debug - Mostrar resultado da criação do diretório /dev/mqueue
  debug:
    var: mqueue_result
    verbosity: 3

- name: Install python pipx via apt package
  become: true
  ansible.builtin.package:
    name: "{{ install_ansible_dev_tools_pipx_package }}"
    state: present
  register: pipx_result

- name: Debug - Mostrar resultado da instalação do pipx
  debug:
    msg: |
      Package: {{ pipx_result.item }}
      State: {{ pipx_result.state }}
      Changed: {{ pipx_result.changed }}
      Failed: {{ pipx_result.failed }}
      Skipped: {{ pipx_result.skipped }}
    loop: "{{ pipx_result.results }}"
    var: pipx_result
    verbosity: 3

- name: Install ansible-dev-tools via pipx
  become: true
  become_user: "{{ install_ansible_dev_tools_v_username }}"
  community.general.pipx:
    name: "{{ install_ansible_dev_tools_ansible_dev_package }}"
    executable: "{{ install_ansible_dev_tools_pipx_executable }}"
    state: present
  register: ansible_dev_tools_result

- name: Debug - Mostrar resultado da instalação do ansible-dev-tools
  debug:
    msg: |
      Package: {{ ansible_dev_tools_result.item }}
      State: {{ ansible_dev_tools_result.state }}
      Changed: {{ ansible_dev_tools_result.changed }}
      Failed: {{ ansible_dev_tools_result.failed }}
      Skipped: {{ ansible_dev_tools_result.skipped }}
    loop: "{{ ansible_dev_tools_result.results }}"
    # Loop through the results to show detailed information
    var: ansible_dev_tools_result
    verbosity: 3 

- name: Ensure that command pipx ensurepath is executed after ansible-dev-tools installation
  become: true
  become_user: "{{ install_ansible_dev_tools_v_username }}"
  ansible.builtin.command: "{{ install_ansible_dev_tools_pipx_executable }} ensurepath"
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin"
  register: pipx_ensurepath_result

- name: Debug - Mostrar resultado da execução do pipx ensurepath
  debug:
    msg: |
      Command: {{ pipx_ensurepath_result.cmd }}
      Changed: {{ pipx_ensurepath_result.changed }}
      Failed: {{ pipx_ensurepath_result.failed }}
      Skipped: {{ pipx_ensurepath_result.skipped }}
    var: pipx_ensurepath_result
    verbosity: 3 

- name: Pull ansible-navigator-demo-ee podman image latest
  containers.podman.podman_image:
    name: quay.io/ansible/ansible-navigator-demo-ee
    tag: latest
  become_user: "{{ install_ansible_dev_tools_v_username }}"
  become: true
  register: podman_image_result

- name: Debug - Mostrar resultado da pull do podman image
  debug:
    msg: |
      Image: {{ podman_image_result.image }}
      Tag: {{ podman_image_result.tag }}
      State: {{ podman_image_result.state }}
      Changed: {{ podman_image_result.changed }}
      Failed: {{ podman_image_result.failed }}
      Skipped: {{ podman_image_result.skipped }}
    var: podman_image_result
    verbosity: 3

- name: Pull ansible-navigator-demo-ee podman image 0.6.0
  containers.podman.podman_image:
    name: quay.io/ansible/ansible-navigator-demo-ee
    tag: 0.6.0
  become_user: "{{ install_ansible_dev_tools_v_username }}"
  become: true
  register: podman_image_0_6_0_result

- name: Debug - Mostrar resultado da pull do podman image 0.6.0
  debug:
    msg: |
      Image: {{ podman_image_0_6_0_result.image }}
      Tag: {{ podman_image_0_6_0_result.tag }}
      State: {{ podman_image_0_6_0_result.state }}
      Changed: {{ podman_image_0_6_0_result.changed }}
      Failed: {{ podman_image_0_6_0_result.failed }}
      Skipped: {{ podman_image_0_6_0_result.skipped }}
    var: podman_image_0_6_0_result
    verbosity: 3

- name: Run source command as user
  ansible.builtin.shell: source ~/.profile
  args:
    executable: /bin/bash
    creates: ~/.profile
  become_user: "{{ install_ansible_dev_tools_v_username }}"
  become: true
  register: source_result

- name: Debug - Mostrar resultado do source ~/.profile
  debug:
    msg: |
      Command: {{ source_result.cmd }}
      Changed: {{ source_result.changed }}
      Failed: {{ source_result.failed }}
      Skipped: {{ source_result.skipped }}
      User: {{ source_result.user }}
      Exit Code: {{ source_result.rc }}
    verbosity: 3