---
- name: Create the /dev/mqueue directory
  ansible.builtin.file:
    path: /dev/mqueue
    state: directory
    mode: '0755'
  become: true
  register: mqueue_result

- name: Debug - Mostrar resultado da criação do diretório /dev/mqueue
  debug:
    var: mqueue_result
    verbosity: 3

- name: Install python pipx via apt package
  become: true
  ansible.builtin.package:
    name: "{{ install_ansible_dev_tools_pipx_package }}"
    state: present
  register: pipx_result

- name: Debug - Mostrar resultado da instalação do pipx
  debug:
    msg: |
      ============================================================
      RESULTADO DA INSTALAÇÃO DO PIPX
      ============================================================
      Package: {{ install_ansible_dev_tools_pipx_package }}
      Changed: {{ pipx_result.changed | default(false) }}
      Failed: {{ pipx_result.failed | default(false) }}
      
      Detalhes Adicionais:
      {{ pipx_result | to_nice_yaml }}
      ============================================================
    verbosity: 3

- name: Install ansible-dev-tools via pipx
  become: true
  become_user: "{{ install_ansible_dev_tools_v_username }}"
  community.general.pipx:
    name: "{{ install_ansible_dev_tools_ansible_dev_package }}"
    executable: "{{ install_ansible_dev_tools_pipx_executable }}"
    state: present
  register: ansible_dev_tools_result

- name: Debug - Mostrar resultado da instalação do ansible-dev-tools
  debug:
    msg: |
      ============================================================
      RESULTADO DA INSTALAÇÃO DO ANSIBLE-DEV-TOOLS
      ============================================================
      Package: {{ install_ansible_dev_tools_ansible_dev_package }}
      Changed: {{ ansible_dev_tools_result.changed | default(false) }}
      Failed: {{ ansible_dev_tools_result.failed | default(false) }}
      
      Detalhes Completos:
      {{ ansible_dev_tools_result | to_nice_yaml }}
      ============================================================
    verbosity: 3 

- name: Ensure that command pipx ensurepath is executed after ansible-dev-tools installation
  become: true
  become_user: "{{ install_ansible_dev_tools_v_username }}"
  ansible.builtin.command: "{{ install_ansible_dev_tools_pipx_executable }} ensurepath"
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin"
  register: pipx_ensurepath_result

- name: Debug - Mostrar resultado da execução do pipx ensurepath
  debug:
    msg: |
      ============================================================
      RESULTADO DA EXECUÇÃO DO PIPX ENSUREPATH
      ============================================================
      Comando: {{ pipx_ensurepath_result.cmd | default('N/A') }}
      Status:
        Changed: {{ pipx_ensurepath_result.changed | default(false) }}
        Failed: {{ pipx_ensurepath_result.failed | default(false) }}
        RC: {{ pipx_ensurepath_result.rc | default('N/A') }}
      
      Detalhes Completos:
      {{ pipx_ensurepath_result | to_nice_yaml }}
      ============================================================
    verbosity: 3 

- name: Pull ansible-navigator-demo-ee podman image latest
  containers.podman.podman_image:
    name: quay.io/ansible/ansible-navigator-demo-ee
    tag: latest
  become_user: "{{ install_ansible_dev_tools_v_username }}"
  become: true
  register: podman_image_result

- name: Debug - Mostrar resultado da pull do podman image
  debug:
    msg: |
      ============================================================
      RESULTADO DO PULL DA IMAGEM PODMAN
      ============================================================
      Imagem:
        Nome: {{ podman_image_result.name | default('N/A') }}
        Tag: {{ podman_image_result.tag | default('N/A') }}
      
      Status:
        Changed: {{ podman_image_result.changed | default(false) }}
        Failed: {{ podman_image_result.failed | default(false) }}
      
      Detalhes Completos:
      {{ podman_image_result | to_nice_yaml }}
      ============================================================
    verbosity: 3

- name: Pull ansible-navigator-demo-ee podman image 0.6.0
  containers.podman.podman_image:
    name: quay.io/ansible/ansible-navigator-demo-ee
    tag: 0.6.0
  become_user: "{{ install_ansible_dev_tools_v_username }}"
  become: true
  register: podman_image_0_6_0_result

- name: Debug - Mostrar resultado da pull do podman image 0.6.0
  debug:
    msg: |
      ============================================================
      RESULTADO DO PULL DA IMAGEM PODMAN 0.6.0
      ============================================================
      Imagem:
        Nome: {{ podman_image_0_6_0_result.name | default('N/A') }}
        Tag: {{ podman_image_0_6_0_result.tag | default('N/A') }}
      
      Status:
        Changed: {{ podman_image_0_6_0_result.changed | default(false) }}
        Failed: {{ podman_image_0_6_0_result.failed | default(false) }}
      
      Detalhes Completos:
      {{ podman_image_0_6_0_result | to_nice_yaml }}
      ============================================================
    verbosity: 3

- name: Run source command as user
  ansible.builtin.shell: source ~/.profile
  args:
    executable: /bin/bash
    creates: ~/.profile
  become_user: "{{ install_ansible_dev_tools_v_username }}"
  become: true
  register: source_result

- name: Debug - Mostrar resultado do source ~/.profile
  debug:
    msg: |
      ============================================================
      RESULTADO DO SOURCE ~/.profile
      ============================================================
      Status:
        Comando: {{ source_result.cmd | default('N/A') }}
        Changed: {{ source_result.changed | default(false) }}
        Failed: {{ source_result.failed | default(false) }}
        RC: {{ source_result.rc | default('N/A') }}
      
      Detalhes Completos:
      {{ source_result | to_nice_yaml }}
      ============================================================
    verbosity: 3