---
- name: Initialize WSL Environment
  hosts: localhost
  gather_facts: true
  vars:
    dev_username: "{{ user }}"
    admin_group: "{{ group }}"
  tasks:
    - name: Create Main User Role
      ansible.builtin.include_role:
        name: create_main_user
      vars:
        create_main_user_v_admin_group: "{{ admin_group }}"
        create_main_user_v_username: "{{ dev_username }}"

    - name: Create Initial Ansible Directory
      ansible.builtin.file:
        path: /ansible
        state: directory
        mode: '0755'
        owner: "{{ dev_username }}"
        group: "{{ dev_username }}"

    - name: Add Fix Script
      ansible.builtin.include_role:
        name: add_fix_script
      vars:
        add_fix_script_v_username: "{{ dev_username }}"

    - name: Setup WSL Network Settings
      ansible.builtin.include_role:
        name: wsl_network_setup
      vars:
        wsl_network_setup_v_username: "{{ dev_username }}"

    - name: Install Certificates
      ansible.builtin.include_role:
        name: load_certificates

    - name: Install podman for Ubuntu
      ansible.builtin.include_role:
        name: install_podman_for_ubuntu
      vars:
        install_podman_for_ubuntu_v_os_version: "{{ hostvars[inventory_hostname].ansible_distribution_version }}"

    - name: Install python pipx
      ansible.builtin.apt:
        pkg:
          - pipx

    - name: Install Ansible Development Tools
      ansible.builtin.include_role:
        name: install_ansible_dev_tools
      vars:
        install_ansible_dev_tools_v_username: "{{ dev_username }}"

    # - name: Install Ansible Navigator
    #   ansible.builtin.include_role:
    #     name: install_ansible_navigator
    #     vars:
    #       v_install_ansible_navigator_username: "{{ dev_username }}"

    # - name: Install ansible python package (already done since running it)
    #   pip:
    #     name: ansible

    # - name: Install ansible-lint python package
    #   pip:
    #     name: ansible-lint

    # - name: Install ansible-builder python package
    #   pip:
    #     name: ansible-builder

    - name: Setup VS Code Settings
      ansible.builtin.include_role:
        name: vs_code_setup
      vars:
        vs_code_setup_v_username: "{{ dev_username }}"
