set_up_pactote_ansible_dev_tools__pipx_package: pipx
set_up_pactote_ansible_dev_tools__ansible_dev_package: ansible-dev-tools
set_up_pactote_ansible_dev_tools__pipx_executable: pipx
set_up_pactote_ansible_dev_tools__ansible_dev_package_args: ""