---
- name: Create initial directories for wsl
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ wsl_network_setup_v_username }}"
    group: "{{ wsl_network_setup_v_username }}"
  loop:
    - '/ansible'
    - '/ansible/default_settings'
    - '/ansible/default_settings/wsl'
  register: create_dirs_result

- name: Debug - Show result of creating directories
  debug:
    msg: |
      Directory: {{ item.item }}
      Result: {{ item.result }}
    loop: "{{ create_dirs_result.results }}"
    verbosity: 3

# -  name: Copy resolv.conf to default settings
#   ansible.builtin.copy:
#     src: "{{ role_path }}/files/resolv.conf"
#     dest: /ansible/default_settings/wsl/resolv.conf
#     mode: '0644'
#     owner: "{{ v_wsl_network_setup_username }}"
#     group: "{{ v_wsl_network_setup_username }}"

# - name: Copy resolv.conf to actual settings
#   ansible.builtin.copy:
#     src: "{{ role_path }}/files/resolv.conf"
#     dest: /etc/resolv.conf
#     mode: '0644'

- name: Copy wsl.conf to default settings
  ansible.builtin.template:
    src: "{{ role_path }}/templates/wsl.conf.j2"
    dest: /ansible/default_settings/wsl/wsl.conf
    mode: '0644'
    owner: "{{ wsl_network_setup_v_username }}"
    group: "{{ wsl_network_setup_v_username }}"
  register: copy_wsl_result

- name: Debug - Show result of copying wsl.conf
  debug:
    msg: |
      Source: {{ item.item.src }}
      Destination: {{ item.item.dest }}
      Result: {{ item.result }}
    loop: "{{ copy_wsl_result.results }}"
    verbosity: 3

- name: Copy wsl.conf to actual settings
  ansible.builtin.template:
    src: "{{ role_path }}/templates/wsl.conf.j2"
    dest: /etc/wsl.conf
    mode: '0644'
  register: copy_wsl_result

- name: Debug - Show result of copying wsl.conf
  debug:
    msg: |
      Source: {{ item.item.src }}
      Destination: {{ item.item.dest }}
      Result: {{ item.result }}
    loop: "{{ copy_wsl_result.results }}"
    verbosity: 3