---
- name: Create initial directories for wsl
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ wsl_network_setup_v_username }}"
    group: "{{ wsl_network_setup_v_username }}"
  loop:
    - '/ansible'
    - '/ansible/default_settings'
    - '/ansible/default_settings/wsl'
  register: create_dirs_result

- name: Debug - Show result of creating directories
  debug:
    msg: |
      ============================================================
      RESULTADO DA CRIAÇÃO DOS DIRETÓRIOS
      ============================================================
      Status:
        Diretórios: {{ create_dirs_result.results | map(attribute='item') | list }}
        Paths: {{ create_dirs_result.results | map(attribute='path') | list }}
        Alterados: {{ create_dirs_result.results | map(attribute='changed') | list }}
      
      Permissões:
        Proprietários: {{ create_dirs_result.results | map(attribute='uid') | list }}
        Grupos: {{ create_dirs_result.results | map(attribute='gid') | list }}
        Modos: {{ create_dirs_result.results | map(attribute='mode') | list }}
      
      Resultados:
        Sucessos: {{ create_dirs_result.results | rejectattr('failed') | list | length }}
        Falhas: {{ create_dirs_result.results | selectattr('failed') | list | length }}
        Estado: {{ create_dirs_result.results | map(attribute='state') | list }}
      ============================================================
    verbosity: 3

# -  name: Copy resolv.conf to default settings
#   ansible.builtin.copy:
#     src: "{{ role_path }}/files/resolv.conf"
#     dest: /ansible/default_settings/wsl/resolv.conf
#     mode: '0644'
#     owner: "{{ v_wsl_network_setup_username }}"
#     group: "{{ v_wsl_network_setup_username }}"

# - name: Copy resolv.conf to actual settings
#   ansible.builtin.copy:
#     src: "{{ role_path }}/files/resolv.conf"
#     dest: /etc/resolv.conf
#     mode: '0644'

- name: Copy wsl.conf to default settings
  ansible.builtin.template:
    src: "{{ role_path }}/templates/wsl.conf.j2"
    dest: /ansible/default_settings/wsl/wsl.conf
    mode: '0644'
    owner: "{{ wsl_network_setup_v_username }}"
    group: "{{ wsl_network_setup_v_username }}"
  register: copy_wsl_default_result

- name: Debug - Show result of copying wsl.conf to default settings
  debug:
    msg: |
      ================================
      RESULTADO DA CÓPIA DO WSL.CONF (DEFAULT)
      ================================
      Source: {{ copy_wsl_default_result.src | default('N/A') }}
      Destination: {{ copy_wsl_default_result.dest | default('N/A') }}
      Changed: {{ copy_wsl_default_result.changed | default(false) }}
      Mode: {{ copy_wsl_default_result.mode | default('N/A') }}
      Failed: {{ copy_wsl_default_result.failed | default(false) }}
      ================================
    verbosity: 3

- name: Copy wsl.conf to actual settings
  ansible.builtin.template:
    src: "{{ role_path }}/templates/wsl.conf.j2"
    dest: /etc/wsl.conf
    mode: '0644'
  register: copy_wsl_actual_result

- name: Debug - Show result of copying wsl.conf to actual settings
  debug:
    msg: |
      ================================
      RESULTADO DA CÓPIA DO WSL.CONF (ATUAL)
      ================================
      Source: {{ copy_wsl_actual_result.src | default('N/A') }}
      Destination: {{ copy_wsl_actual_result.dest | default('N/A') }}
      Changed: {{ copy_wsl_actual_result.changed | default(false) }}
      Mode: {{ copy_wsl_actual_result.mode | default('N/A') }}
      Failed: {{ copy_wsl_actual_result.failed | default(false) }}
      ================================
    verbosity: 3