---
- name: Create Initial Ansible Directory
  ansible.builtin.file:
    path: /ansible
    state: directory
    mode: '0755'
    owner: "{{ add_fix_script_v_username }}"
    group: "{{ add_fix_script_v_username }}"
  register: create_ansible_dir_result

- name: Debug - Show result of creating Ansible directory
  debug:
    msg: |
      Directory: {{ create_ansible_dir_result.path }}
      State: {{ create_ansible_dir_result.state }}
      Owner: {{ create_ansible_dir_result.owner }}
      Group: {{ create_ansible_dir_result.group }}
      Mode: {{ create_ansible_dir_result.mode }}
      Changed: {{ create_ansible_dir_result.changed }}
      Failed: {{ create_ansible_dir_result.failed }}
      Skipped: {{ create_ansible_dir_result.skipped }}       
    loop: "{{ create_ansible_dir_result.results }}"
    verbosity: 3

- name: Copy Fix Script To Ansible Directory
  ansible.builtin.template:
    src: "{{ role_path }}/templates/fix.sh.j2"
    dest: /ansible/fix.sh
    mode: '0775'
    owner: "{{ add_fix_script_v_username }}"
    group: "{{ add_fix_script_v_username }}"
  register: copy_fix_script_result

- name: Debug - Show result of copying fix.sh
  debug:
    msg: |
      Source: {{ copy_fix_script_result.src }}
      Destination: {{ copy_fix_script_result.dest }}
      Owner: {{ copy_fix_script_result.owner }}
      Group: {{ copy_fix_script_result.group }}
      Mode: {{ copy_fix_script_result.mode }}
      Changed: {{ copy_fix_script_result.changed }}
      Failed: {{ copy_fix_script_result.failed }}
      Skipped: {{ copy_fix_script_result.skipped }}      
    loop: "{{ copy_fix_script_result.results }}"
    verbosity: 3