---
- name: Create Initial Ansible Directory
  ansible.builtin.file:
    path: /ansible
    state: directory
    mode: '0755'
    owner: "{{ add_fix_script_v_username }}"
    group: "{{ add_fix_script_v_username }}"
  register: create_ansible_dir_result

- name: Debug - Show result of creating Ansible directory
  debug:
    msg: |
      ================================
      RESULTADO DA CRIAÇÃO DO DIRETÓRIO
      ================================
      Directory: {{ create_ansible_dir_result.path }}
      Changed: {{ create_ansible_dir_result.changed }}
      Mode: {{ create_ansible_dir_result.mode }}
      Owner: {{ create_ansible_dir_result.uid }}
      Group: {{ create_ansible_dir_result.gid }}
      State: {{ create_ansible_dir_result.state | default('N/A') }}
      Failed: {{ create_ansible_dir_result.failed | default(false) }}
      ================================
      Todas as Variáveis Disponíveis:
      {{ create_ansible_dir_result | to_nice_yaml }}
      ================================
    verbosity: 3

- name: Copy Fix Script To Ansible Directory
  ansible.builtin.template:
    src: "{{ role_path }}/templates/fix.sh.j2"
    dest: /ansible/fix.sh
    mode: '0775'
    owner: "{{ add_fix_script_v_username }}"
    group: "{{ add_fix_script_v_username }}"
  register: copy_fix_script_result

- name: Debug - Show result of copying fix.sh
  debug:
    msg: |
      ================================
      RESULTADO DA CÓPIA DO SCRIPT
      ================================
      Source: {{ copy_fix_script_result.src | default('N/A') }}
      Destination: {{ copy_fix_script_result.dest | default('N/A') }}
      Changed: {{ copy_fix_script_result.changed | default(false) }}
      Failed: {{ copy_fix_script_result.failed | default(false) }}
      ================================
      Dados Completos:
      {{ copy_fix_script_result | to_nice_yaml }}
      ================================
    verbosity: 3